### ISSUE TITLE
Missing node['cassandra']['log_config_files']

### ISSUE THREAD

**Issue by rogeralmeida** [michaelklishin/cassandra-chef-cookbook#184]
Hi,
I getting the following error:
```
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: filtered backtrace of compile error: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: filtered backtrace of compile error: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: backtrace entry for compile error: '/tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file''
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: Line number of compile error: '132'
==> Node1:
==> Node1: ================================================================================
==> Node1: Recipe Compile Error in /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb
==> Node1: ================================================================================
==> Node1:
==> Node1:
==> Node1: NoMethodError
==> Node1: -------------
==> Node1: undefined method `each' for nil:NilClass
==> Node1:
==> Node1:
==> Node1: Cookbook Trace:
==> Node1:
==> Node1: ---------------
==> Node1:   /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1:
==> Node1: Relevant File Content:
==> Node1: ----------------------
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:
==> Node1:
==> Node1: 125:      owner node['cassandra']['user']
==> Node1: 126:      group node['cassandra']['group']
==> Node1: 127:      mode 0644
==> Node1: 128:      notifies :restart, 'service[cassandra]', :delayed if node['cassandra']['notify_restart']
==> Node1: 129:    end
==> Node1: 130:  end
==> Node1: 131:
==> Node1: 132>> node['cassandra']['log_config_files'].each do |f|
==> Node1: 133:    template ::File.join(node['cassandra']['conf_dir'], f) do
==> Node1: 134:      cookbook node['cassandra']['templates_cookbook']
==> Node1: 135:      source "#{f}.erb"
==> Node1: 136:      owner node['cassandra']['user']
==> Node1: 137:      group node['cassandra']['group']
==> Node1: 138:      mode '0644'
==> Node1: 139:      notifies :restart, 'service[cassandra]', :delayed if node['cassandra']['notify_restart']
==> Node1: 140:    end
==> Node1: 141:  end
==> Node1:
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: Re-raising exception: NoMethodError - undefined method `each' for nil:NilClass
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:446:in `run'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> Node1:   /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> Node1:   /usr/bin/chef-solo:52:in `load'
==> Node1:   /usr/bin/chef-solo:52:in `<main>'
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: Running exception handlers
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: Exception handlers complete
==> Node1: [2015-03-28T14:33:52+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: NoMethodError: undefined method `each' for nil:NilClass
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/client.rb:446:in `run'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> Node1: /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> Node1: /usr/bin/chef-solo:52:in `load'
==> Node1: /usr/bin/chef-solo:52:in `<main>'
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: undefined method `each' for nil:NilClass
==> Node1: [2015-03-28T14:33:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Looks like the recipe is missing the `node['cassandra']['log_config_files']` attribute.
I guess that this merge can be the cause:
https://github.com/michaelklishin/cassandra-chef-cookbook/commit/9a2a4929f2cc9d4439e9abe377852002344a47b5#diff-25e5d4a4446ae12a0d6f1162b6160375

My Vagrantfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Cassandra Cluster Settings
server_count = 3
network = '10.0.1.'
first_ip = 10
cluster_name = 'Cassandra-Cluster'
# vars
servers = []
seeds = []
cassandra_tokens = []
# Generate server configs
(0..server_count-1).each do |i|
	name = 'Node' + (i + 1).to_s
	ip = network + (first_ip + i).to_s
	seeds << ip
	servers << {'name' => name,
						 'ip' => ip,
						 'initial_token' => 2**127 / server_count * i
	}
end
Vagrant.configure(2) do |config|
	# The most common configuration options are documented and commented below.
	# For a complete reference, please see the online documentation at
	# https://docs.vagrantup.com.

	# Every Vagrant development environment requires a box. You can search for
	# boxes at https://atlas.hashicorp.com/search.
	config.berkshelf.enabled = true
	config.omnibus.chef_version = :latest
	config.vbguest.auto_update = false
	servers.each do |server|
		config.vm.define server['name'] do |machine|
			machine.vm.box = "chef/centos-6.5"
			machine.vm.hostname = server['name']
			machine.vm.network :private_network, ip: server['ip']
			machine.vm.provider "virtualbox" do |v|
				v.name = cluster_name.gsub(/\s*/, '') + '-' + server['name']
			end

			machine.vm.provision :chef_solo do |chef|
				chef.log_level = :debug
				chef.add_recipe "apt"
				chef.add_recipe "java"
				chef.add_recipe "cassandra::tarball"
				chef.json = {
					:cassandra => {
						'cluster_name' => cluster_name,
						'initial_token' => server['initial_token'],
						'seeds' => seeds,
						'listen_address' => server['ip'],
						'rpc_address' => server['ip']
					},
					:java => {
						'install_flavor' => "oracle",
						'jdk_version' => "7",
						'oracle' => {
							'accept_oracle_download_terms' => true
						}
					}
				}
			end
		end
	end
end
```
My Berksfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

site :opscode

cookbook 'apt'
cookbook 'java'
cookbook 'cassandra', git: 'https://github.com/michaelklishin/cassandra-chef-cookbook.git'
```
Any thought about how to solve it locally? Or should I fork, add the attribute, test and submit a pull request?

**Comment by rogeralmeida** [comment]
Sorry, to reproduce you just have to run a `vagrant up` the first time or a `vagrant provision Node1` if you already have the machine created.

**Comment by rogeralmeida** [comment]
More data, my vagrant plugins:
```bash
$ vagrant plugin list
vagrant-berkshelf (4.0.3)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)
```

**Comment by vkhatri** [comment]
@rogeralmeida you are right, attribute is indeed missing. attributes were moved from attributes to datastax recipe.

i will take a look at it.

**Comment by mexey89** [comment]
add include_recipe 'cassandra::datastax' to your tarball.rb in recipes.

**Comment by zanzan42** [comment]
Anybody going to fix this for those of us on Amazon Linux who need the cassandra::tarball to work? It's June already... :-)

I guess I'll copy the cookbook into my custom OpsWorks cookbook and fix it locally for now, but I'd really like to just refer to this cookbook in my berksfile instead.

**Comment by michaelklishin** [comment]
@zanzan42 this is open source software. You can fix it "here".

**Comment by zanzan42** [comment]
Not when you work for a Fortune 500 that doesn't let you do that.

**Comment by michaelklishin** [comment]
@zanzan42 I realise it's not your fault but this is pretty ridiculous: a large corporation begging volunteers to fix a freely available project for them so that they can deploy their stuff.

I'll take a look this weekend. Open source is corporate welfare and I have a (tiny) heart.

**Comment by zanzan42** [comment]
I should clarify: we do a lot of open source contribution, but only specific people/groups are allowed to work in that space, and I'm not one of them. The amount of legal hurdles I'd have to go through to become one is of epic proportions. Since I'm not a developer, it's simply not going to happen.

**Comment by zanzan42** [comment]
There are four attributes that tarball.rb references which are missing from the attributes file:

default['cassandra']['log_config_files'] = %w(log4j-server.properties)
default['cassandra']['jamm_version'] = '0.2.5'
default['cassandra']['jamm']['base_url'] = "http://repo1.maven.org/maven2/com/github/stephenc/jamm/#{node.attribute['cassandra']['jamm_version']}"
default['cassandra']['jamm']['jar_name'] = "jamm-#{node.attribute['cassandra']['jamm_version']}.jar"
default['cassandra']['jamm']['sha256sum'] = 'e3dd1200c691f8950f51a50424dd133fb834ab2ce9920b05aa98024550601cc5'

After adding these back in (and, for now, ignoring any issues around checking whether your using old or new cassandra versions, as the datastax.rb does), my OpsWorks chef run gets almost to the end before choking on something else:

================================================================================
Error executing action `create` on resource 'template[/usr/local/cassandra/conf/cassandra.yaml]'
================================================================================
 
 
Chef::Mixin::Template::TemplateError
------------------------------------
undefined method `each' for "/local/mnt/cassandra/data":String
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/cassandra/recipes/tarball.rb
 
123:   template ::File.join(node['cassandra']['conf_dir'], f) do
124:     source "#{f}.erb"
125:     owner node['cassandra']['user']
126:     group node['cassandra']['group']
127:     mode 0644
128:     notifies :restart, 'service[cassandra]', :delayed if node['cassandra']['notify_restart']
129:   end
130: end
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/cassandra/recipes/tarball.rb:123:in `block in from_file'
 
template("/usr/local/cassandra/conf/cassandra.yaml") do
provider Chef::Provider::Template
action "create"
retries 0
retry_delay 2
path "/usr/local/cassandra/conf/cassandra.yaml"
backup 5
atomic_update true
source "cassandra.yaml.erb"
cookbook_name "cassandra"
recipe_name "tarball"
mode 420
owner "cassandra"
group "cassandra"
end
 
 
 
Template Context:
-----------------
on line #118
116: # directories where Cassandra should store data on disk.
117: data_file_directories:
118: <% node['cassandra']['data_dir'].each do |data_dir| -%>
119:     - <%= data_dir %>
120: <% end %>
 
 
[2015-06-05T18:46:43+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-06-05T18:46:43+00:00] ERROR: Running exception handlers
[2015-06-05T18:46:43+00:00] ERROR: Exception handlers complete
[2015-06-05T18:46:43+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-06-05T18:46:43+00:00] ERROR: 
 
Chef::Mixin::Template::TemplateError (undefined method `each' for "/local/mnt/cassandra/data":String) on line #118:
 
116: # directories where Cassandra should store data on disk.
117: data_file_directories:
118: <% node['cassandra']['data_dir'].each do |data_dir| -%>
119:     - <%= data_dir %>
120: <% end %>

In the tarball.rb ['cassandra']['data_dir'] is simply a single string, not an array. I think that's why I get undefined method for 'each'. In the datastax.rb, the data_dir is actually defined as an array.

Change that code block to simply populate the line with the single data_dir value:

data_file_directories:
    - <%= node['cassandra']['data_dir'] %>

And the OpsWorks chef run completes. I still have to check and see that cassandra itself is actually working, though.

I suppose that defining the data_dir attribute as an array in the tarball.rb, rather than changing the template, would likely solve the issue as well.

**Comment by zanzan42** [comment]
Looks like the yaml template includes some things that cassandra 2.0.15 (latest) doesn't like, either:

 INFO 20:39:11,546 Logging initialized
 INFO 20:39:11,598 Loading settings from file:/usr/local/apache-cassandra-2.0.15/conf/cassandra.yaml
ERROR 20:39:12,009 Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [counter_write_request_timeout_in_ms, sstable_preemptive_open_interval_in_mb, index_summary_capacity_in_mb, counter_cache_size_in_mb, concurrent_counter_writes, memtable_allocation_type, broadcast_rpc_address, counter_cache_save_period, index_summary_resize_interval_in_minutes] from your cassandra.yaml

**Comment by michaelklishin** [comment]
@zanzan42 thank you!
