### ISSUE TITLE
cassandra.yaml template issue

### ISSUE THREAD

**Issue by akkinenivijay** [michaelklishin/cassandra-chef-cookbook#242]
When default['cassandra']['version'] = '2.0.11', the cassandra.yaml generated includes broadcast_rpc_address and other properties not relevant to 2.0.x. This is on version 4.0.0

**Comment by vkhatri** [comment]
@akkinenivijay Could you please share your `wrapper recipe / role` etc. details? I suspect it could be happening due to the derived attributes precedence mainly caused when using wrapper cookbook.

@michaelklishin I have been thinking to introduce this change in the cookbook from some time. Resolution is to move all derived attributes to a separate recipe `recipes/attributes` instead of evaluating them in an attributes file.

**Comment by akkinenivijay** [comment]
default.rb
default[:cassandra][:version] = '2.0.11'
default[:cassandra][:package_name] = 'dsc20'
default[:cassandra][:installation_dir] = "/etc/cassanda"

include_recipe 'cassandra-dse::default'

I think the conditional evaluation of version check in attributes/config.rb, should be deferred to template generation recipe, so that the wrapper cookbooks can dictate the version override.

**Comment by michaelklishin** [comment]
@akkinenivijay isn't this why Chef has override attributes?

@vkhatri I trust your judgements but wrapper cookbooks is not a particularly strong argument for me given that Chef provides them a way to override *a lot* with little effort.

**Comment by vkhatri** [comment]
@michaelklishin Thank you, I have been meaning to discuss it from sometime. Perhaps, adding a section on how to use a wrapper cookbook could be a good idea. Will work on it.

@akkinenivijay We were evaluating different version specific attributes in `cassandra.yaml`, but that did not take us too far with too many `versions`.

Could you please try updating attributes with `override` and let us know if that works for you?

**Comment by akkinenivijay** [comment]
@michaelklishin @vkhatri  override worked.
