### ISSUE TITLE
Support for apache-cassandra going forward?

### ISSUE THREAD

**Issue by Highstead** [michaelklishin/cassandra-chef-cookbook#364]
With datastax no longer supporting the community edition what is the intention for this cookbook?

**Comment by chrismoos** [comment]
@Highstead I was able to get the latest community edition (3.11.1) running with the `tarball` install, maybe this needs to be the default going forward as the DSC version is a bit out of date now.

```
default['cassandra']['version'] = "3.11.1"
default['cassandra']['install_method'] = 'tarball'
default['cassandra']['tarball']['sha256sum'] = '6feed696759e2f3219e0ebde13f4c9080cac0744a77eb3cb43af136ab527f0ed'
default['java']['jdk_version'] = '8'
```

**Comment by michaelklishin** [comment]
@Highstead this cookbook was never maintained by DataStax or focussed primarily on DSE.

**Comment by michaelklishin** [comment]
I now see this may be related to a few findings in #333. Long story short, I'm open to switching to a different package source/repo for open source Cassandra. Pull requests that address this are welcome.

I'm also happy to add more folks as contributors so that changes are merged quicker and releases are done faster. I have dozens of open source projects on my hands and admittedly miss PRs more often than I'd like to. So raise your hand if you are interested in becoming a co-maintainer :)

**Comment by michaelklishin** [comment]
@chrishenry no objections to switching to tarball-based provisioning by default. Please submit a PR :)

**Comment by sethrosenblum** [comment]
Apache maintains their own repo for Cassandra now which might help with this: http://dl.bintray.com/apache/cassandra/dists/

The biggest problem is that they don't keep older versions in their package lists, so pinning a version would break the cookbook whenever they release a minor update.
